version: '3.4'
    
services:
  redis-node1:
    build:
      context: .
    ports:
      - "6379:6379"
    restart: always
    container_name: redis-1
    entrypoint: [redis-server, /etc/redis/redis-cluster.conf, --port,"6379"]

  redis-node2:
    build:
      context: .
    ports:
      - "6380:6380"
    restart: always
    container_name: redis-2
    entrypoint: [redis-server, /etc/redis/redis-cluster.conf,--port,"6380"]

  redis-node3:
    build:
      context: .
    ports:
      - "6381:6381"
    restart: always
    container_name: redis-3
    entrypoint: [redis-server, /etc/redis/redis-cluster.conf,--port,"6381"]

  redis-cluster-creator:
    image: redis:7.0
    entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli --cluster create redis-1:6379 redis-2:6380 redis-3:6381  --cluster-replicas 0']
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
