{
 "title": "Redis",
 "description": "Redis",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up{job=\"redis_exporter_targets\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[$interval])) by (instance)) * 100",
       "legendFormat": "{{instance}} : usage"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100",
       "legendFormat": "{{instance}} : usage"
      }
     ]
    }
   ]
  },
  { "title": "redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Connected clients",
   "type": "graph",
   "description": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Requests / sec." }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}:{{port}} - clients"
    }
   ]
  },
  {
   "title": "keyspace_hitrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(redis_keyspace_hits_total{instance=~\"$instance\"}/(redis_keyspace_hits_total{instance=~\"$instance\"}+redis_keyspace_misses_total{instance=~\"$instance\"}))*100",
     "legendFormat": "{{instance}}:{{port}} - hitrate"
    }
   ]
  },
  {
   "title": "keyspace_hits",
   "type": "graph",
   "description": "counter",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "waiting & writing" }
   ],
   "targets": [
    {
     "expr": "rate(redis_keyspace_hits_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}:{{port}} - hits"
    }
   ]
  },
  {
   "title": "keyspace_misses",
   "type": "graph",
   "description": "counter",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "waiting & writing" }
   ],
   "targets": [
    {
     "expr": "rate(redis_keyspace_misses_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}:{{port}} - misses"
    }
   ]
  },
  {
   "title": "instantaneous_ops_per_sec",
   "type": "graph",
   "description": "counter",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops", "label": "waiting & writing" }
   ],
   "targets": [
    {
     "expr": "rate(redis_instantaneous_ops_per_sec{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}:{{port}}"
    }
   ]
  },
  {
   "title": "instantaneous_input_kbps",
   "type": "graph",
   "description": "counter",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "KBs", "label": "waiting & writing" }
   ],
   "targets": [
    {
     "expr": "rate(redis_instantaneous_input_kbps{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}:{{port}}"
    }
   ]
  },
  {
   "title": "instantaneous_output_kbps",
   "type": "graph",
   "description": "counter",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "KBs", "label": "waiting & writing" }
   ],
   "targets": [
    {
     "expr": "rate(redis_instantaneous_output_kbps{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}:{{port}}"
    }
   ]
  },
  {
   "title": "keyspace_total_input_network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "decbytes", "label": "waiting & writing" }
   ],
   "targets": [
    {
     "expr": "rate(redis_keyspace_total_input_network{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}:{{port}} - input"
    }
   ]
  },
  {
   "title": "keyspace_total_output_network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decbytes", "label": "waiting & writing" }
   ],
   "targets": [
    {
     "expr": "rate(redis_keyspace_total_output_network{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}:{{port}} - input"
    }
   ]
  },
  {
   "title": "connections",
   "type": "graph",
   "description": "counter",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "waiting & writing" }
   ],
   "targets": [
    {
     "expr": "rate(redis_connections{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}:{{port}} - connections"
    }
   ]
  },
  {
   "title": "Used memory (rss)",
   "type": "graph",
   "description": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_rss_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}:{{port}} - rss"
    }
   ]
  },
  {
   "title": "Used memory (peak)",
   "type": "graph",
   "description": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_peak_bytes{instance=~\"$instance\"} ",
     "legendFormat": "{{instance}}:{{port}} - peak"
    }
   ]
  }
 ]
}